#!/bin/bash
echo "Testing Logistics Management System..."
echo "1. Starting application..."
echo "2. You should see a login window with:"
echo "   - Username and Password fields"
echo "   - Login and Cancel buttons"
echo "   - Register New User button"
echo ""
echo "3. Test the following:"
echo "   - Login with admin/admin123 (Admin dashboard)"
echo "   - Login with user/user123 (User dashboard)"
echo "   - Click 'Register New User' to create new users"
echo "   - In User dashboard, try creating a shipment"
echo ""
echo "4. Default test data:"
echo "   - Sender City: New York"
echo "   - Receiver City: Los Angeles"
echo "   - Distance: 500"
echo "   - Weight: 10"
echo "   - Priority: Normal"
echo "   - Traffic: Normal"
echo "   - Transport: Road"
echo ""
echo "Starting application now..."
java -cp "target/classes:lib/sqlite-jdbc-3.44.1.0.jar:lib/slf4j-api-1.7.36.jar:lib/slf4j-simple-1.7.36.jar" com.logistics.LogisticsManagementSystem
